DROP TABLE IF EXISTS  mdm.org_addtl_info CASCADE;

CREATE TABLE mdm.org_addtl_info (
	org_info_id varchar(50) NOT NULL,
	org_id varchar(50) NOT NULL,
	org_info_key varchar(500) NOT NULL,
	type_cd varchar(50) NOT NULL,
	attrib_01 varchar(100) NULL,
	attrib_02 varchar(100) NULL,
	attrib_03 varchar(100) NULL,
	attrib_04 varchar(100) NULL,
	attrib_05 varchar(100) NULL,
	attrib_06 date NULL,
	attrib_07 date NULL,
	attrib_08 date NULL,
	attrib_09 date NULL,
	attrib_10 date NULL,
	attrib_11 numeric NULL,
	attrib_12 numeric NULL,
	attrib_13 numeric NULL,
	attrib_14 numeric NULL,
	attrib_15 numeric NULL,
	attrib_16 numeric NULL,
	attrib_17 numeric NULL,
	attrib_18 numeric NULL,
	attrib_19 numeric NULL,
	attrib_20 numeric NULL,
	attrib_21 bpchar(1) NULL,
	attrib_22 bpchar(1) NULL,
	attrib_23 bpchar(1) NULL,
	attrib_24 bpchar(1) NULL,
	attrib_25 bpchar(1) NULL,
	attrib_26 varchar(100) NULL,
	attrib_27 varchar(100) NULL,
	attrib_28 varchar(100) NULL,
	attrib_29 varchar(100) NULL,
	attrib_30 varchar(100) NULL,
	attrib_31 bpchar(3) NULL,
	attrib_32 bpchar(3) NULL,
	attrib_33 bpchar(3) NULL,
	attrib_34 bpchar(3) NULL,
	attrib_35 bpchar(2) NULL,
	attrib_36 bpchar(2) NULL,
	attrib_37 bpchar(2) NULL,
	attrib_38 bpchar(2) NULL,
	attrib_39 text NULL,
	attrib_40 text NULL,
	attrib_41 bytea NULL,
	start_dt date NOT NULL,
	end_dt date NULL,
	created_by varchar(50) NOT NULL,
	created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_by varchar(50) NOT NULL,
	updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT org_addtl_info_pkey PRIMARY KEY (org_info_id),
	CONSTRAINT org_addtl_info_org_id_fkey FOREIGN KEY (org_id) REFERENCES mdm.organisation(org_id)
);