DROP TABLE IF EXISTS scheduler.BATCH_JOB_EXECUTION_CONTEXT CASCADE ;

CREATE TABLE scheduler.BATCH_JOB_EXECUTION_CONTEXT  (
JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
SHORT_CONTEXT VARCHAR(2500) NOT NULL,
SERIALIZED_CONTEXT TEXT ,
constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
references scheduler.BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;