insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'ADDR_TYPE',	'Address Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'AIRE_RULE_TYPE',	'AIRE Rule Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'RR_METHOD',	'Round Robin Method',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'RR_COUNTER',	'Round Robin Counter Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'AIRE_STATUS',	'AIRE Status',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'PARTY_TYPE',	'Party Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'ORG_STATUS',	'Organisation Status',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'CUST_TYPE',	'Customer Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'PARTY_REL_TYPE',	'Party Relationship Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'ADDR_REL_TYPE',	'Address Relationship Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'EXTRNL_TYPE',	'Party External Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'STATUS',	'Status',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'ORG_ADDTL_INFO',	'Org Addtl Info Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'KEY_TYPE',	'Key Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'FRD_CATEGORY',	'Fraud Category',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'FRD_CAT_TYPE',	'Fraud Category Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'PRODUCT_TYPE',	'Product Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'MSG_RELATIONSHIP',	'Message Relatiionship',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'CHANNEL',	'Email Channel',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'COMM_FIELD_TYPE',	'Communication Field Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'DATA_MAP_TYPE',	'Data Map Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'EVENT_STATUS',	'Event Status',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'EVENT_REL_TYPE',	'Event Relationship Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'EVENT_LOG_STATUS',	'Event Log Status',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'TXN_REQUEST_TYPE',	'Transaction Request Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'WEBHOOK_STATUS',	'Webhook Status',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'RECUR_TYPE',	'Recurring Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'CHANNEL_CD',	'Channel',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'WEBHOOK_INTRVL',	'Webhook Interval',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'CARD_TYPE',	'Card Type',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'WEEK_DAYS',	'Week Days',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'THREEDS_VERSION',	'3DS Version',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
insert into mdm.lookup(lookup,desc_txt,active_flg,created_by,created_at,updated_by,updated_at) VALUES(	'TXN_STATUS',	'Transaction Status',	 'Y','APEXX',CURRENT_DATE,'APEXX',CURRENT_DATE);
commit;